version: "3.8"
services:
  app:
    container_name: app
    build: .
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "5555:5555"
    volumes:
      - type: bind
        source: .
        target: /workspaces
    env_file:
      - .env

  db:
    image: postgres
    container_name: my_postgres
    ports:
     - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
